version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cupcake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cupcake_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
